### ISSUE TITLE
Broken link for OS X dmg installer.

### ISSUE THREAD

**Issue by Bill-Costa** [yyosifov/image-viewer#37]
"OS X: Image Viewer.dmg" points to `https://github.com/yyosifov/image-viewer/raw/master/dist/Image%20Viewer-1.1.0.dmg` which comes up with a 404 error.

**Comment by yyosifov** [comment]
Thanks for reporting this. I fixed the link - pointing to the first version 1.1.0:

`https://github.com/yyosifov/image-viewer/raw/yo/image-viewer-v1/dist/Image%20Viewer-1.1.0.dmg` 

Unfortunately, I haven't fixed the build of the installer for the latest version.
